### ISSUE TITLE
ez package - by Evan Muzzall

### ISSUE THREAD

**Issue by EastBayEv** [EastBayEv/Deep-Learning-in-R#2]
ez functions for machine learning
	◦	ez_cdp: auto create data partition by specifying a dataset for training and testing
	◦	ez_mlplot: create automated visualizations of machine learning visualizations
	◦	ez_import: auto import a directory of images for deep learning
	◦	ez_keras: automatically build your NN using interactive dialogue

**Comment by ck37** [comment]
You should start up a repo for this package - closing the issue in this repo
